services:
  - type: web
    name: waste-mitra
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn waste_management.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GEMINI_API_KEY
        sync: false
